### ISSUE TITLE
the guy who made this is a nerd

### ISSUE THREAD

**Issue by OKatiepowersO** [BuzzyAxolotls/BuzzyAxolotls#13]
he is a big ole nerd but also STINKS!! like big time like everyone i know says wow this guy is super cool its a shame he STINKS SO BAD!!

**Comment by BuzzyAxolotls** [comment]
nuh uh

**Comment by OKatiepowersO** [comment]
uh yeah huh you STINKKKKKKKK TAKE A SHOOOOWWERR WITH ME!! whaaat who said this clearly this guy just hacked into my acc to say that whaat thats crazy
